import { ReactNode } from "react";

export type ItemGroup = {
  groupName: string;
  elements: string[];
  icon?: ReactNode;
};

export interface ItemParentGroup {
  parentGroupName: string;
  children: ItemGroup[];
}

export const parentGroups = new Map([
  ["birds", ["birds", "cassowary", "penguin"]],
  [
    "game",
    [
      "kangaroo",
      "antelope",
      "deer",
      "rabbit",
      "monkey",
      "rat",
      "wombat",
      "game",
    ],
  ],
  [
    "domesticated meat",
    [
      "camel",
      "charqui",
      "chicken",
      "cow & ox",
      "ducks",
      "goat",
      "horses",
      "pig",
      "sheep",
      "guinea pigs",
      "llama",
      "fat-tailed sheep with hair instead of wool",
    ],
  ],
  ["large game", ["elephant"]],
  ["reptiles", ["lizard", "frog", "snake"]],
  ["stews and soups and processed", ["bread", "soup", "stew", "porridge"]],
  ["grains", ["barley", "wheat", "maize", "rice"]],
  [
    "fish & ocean mammals",
    [
      "cod",
      "dolphins",
      "lobster",
      "porpoise",
      "seal",
      "sharks",
      "toothfish",
      "tunny",
      "whale",
      "fish",
    ],
  ],
  [
    "fruits and vegetables",
    [
      "banana",
      "berries",
      "coconut",
      "dried fruit",
      "mash",
      "potatoes",
      "nutty beans",
      "peppers",
      "onions",
      "pumpkin",
      "plums",
      "raisins",
      "turnips",
      "vegetables",
      "yam",
      "yellow fruit",
      "seaweed",
    ],
  ],
  ["nuts and so", ["chestnuts", "cocoa nuts", "mushroom", "roots"]],
  [
    "spices & other",
    ["spices", "cardamom", "pepper", "tumeric", "anise", "sugar"],
  ],
  ["special", ["blood", "liver", "meat", "ice"]],
]);

export const foodGroups = new Map([
  ["anise", ["anise"]],
  ["antelope", ["antelope", "antelopes"]],
  ["banana", ["banana", "bananas"]],
  ["barley", ["barley"]],
  ["berries", ["berries"]],
  ["birds", ["birds"]],
  ["blood", ["blood"]],
  ["buffalo", ["buffalo"]],
  ["bread", ["dough", "bread"]],
  ["camel", ["camel", "camels"]],
  ["cardamom", ["cardamom"]],
  ["cassowary", ["cassowaries", "cassowary"]],
  ["charqui", ["charqui"]],
  ["chestnuts", ["chestnuts"]],
  ["chicken", ["chicken", "chickens", "poultry"]],
  ["cocoa nut", ["cocoa nut"]],
  ["coconut", ["coconut"]],
  ["cod", ["cod"]],
  [
    "cow & ox",
    ["cow", "beef", "cows", "cattle", "ox", "oxen", "veal", "oxheads"],
  ],
  ["deer", ["deer", "venison"]],
  ["dolphins", ["dolphins", "dolphin"]],
  ["dried fruit", ["dried fruit"]],
  ["ducks", ["duck", "ducks"]],
  ["elephant", ["elephant", "elephants"]],
  [
    "fat-tailed sheep with hair instead of wool",
    ["fat-tailed sheep with hair instead of wool"],
  ],
  ["fish", ["fish"]],
  ["frog", ["frog", "frogs"]],
  ["game", ["game"]],
  ["goat", ["goat", "goats"]],
  ["guinea pigs", ["guinea pigs"]],
  ["horse", ["horse", "horses", "burnt horse", "horse carcass", "horsemeat"]],
  ["ice", ["ice"]],
  ["kangaroo", ["kangaroo", "kangaroos"]],
  ["llama", ["llama", "llamas"]],
  ["lizard", ["lizard", "lizards"]],
  ["liver", ["liver in sauce"]],
  ["lobster", ["lobsters", "lobster"]],
  ["maize", ["maize"]],
  ["mash", ["mash"]],
  ["meat", ["meat"]],
  ["monkey", ["monkey livers"]],
  ["mushroom", ["mushrooms", "mushroom"]],
  ["nutty beans", ["nutty beans"]],
  ["onions", ["onions"]],
  ["penguin", ["penguin", "penguins"]],
  ["pepper", ["pepper"]],
  ["peppers", ["peppers"]],
  ["pig", ["pig", "pigs", "hogs", "hog", "pork"]],
  ["porpoise", ["porpoise"]],
  ["porridge", ["porridge"]],
  ["potatoes", ["potatoes"]],
  ["plums", ["plums"]],
  ["pumpkin", ["pumpkin"]],
  ["rat", ["rat", "rats", "rodents"]],
  ["rabbit", ["with rabbit"]],
  ["raisins", ["raisins"]],
  ["rice", ["rice"]],
  ["sugar", ["rock sugar"]],
  ["roots", ["roots"]],
  ["seal", ["seal", "seals"]],
  ["seaweed", ["seaweed"]],
  ["shark", ["sharks", "shark"]],
  ["sheep", ["sheep", "lamb", "lambs", "mutton"]],
  ["snake", ["snake", "snakes"]],
  ["stew", ["stew"]],
  ["soup", ["soup"]],
  ["spices", ["spices"]],
  ["toothfish", ["toothfish"]],
  ["tumeric", ["tumeric"]],
  ["tunny", ["tunny", "tunnys"]],
  ["turnips", ["turnips"]],
  ["vegetables", ["vegetables"]],
  ["whale", ["whale", "whales"]],
  ["wheat", ["wheat", "grain", "grains"]],
  ["wombat", ["wombat", "wombats"]],
  ["yam", ["local yam"]],
  ["yellow fruit", ["small yellow fruits"]],
]);
